export const USER = 'USER';
export const ROLE = 'ROLE';
export const CURRENCY = 'CURRENCY';
export const LAYOUT = 'LAYOUT';
export const COMPANY = 'COMPANY';
export const ADMINISTRATION_CHART_ACCOUNT = 'ADMINISTRATION_CHART_ACCOUNT';
export const ADMINISTRATION_BRAND = 'ADMINISTRATION_BRAND';
export const ADMINISTRATION_CATEGORY = 'ADMINISTRATION_CATEGORY';
export const ADMINISTRATION_TRANSACTION_TYPE = 'ADMINISTRATION_TRANSACTION_TYPE';
export const ADMINISTRATION_TAX_TYPE = 'ADMINISTRATION_TAX_TYPE';
export const ADMINISTRATION_UNIT_OF_MEASURE = 'ADMINISTRATION_UNIT_OF_MEASURE';
export const ADMINISTRATION_PAYMENT_METHOD = 'ADMINISTRATION_PAYMENT_METHOD';
export const ADMINISTRATION_INCOME_TYPE = 'ADMINISTRATION_INCOME_TYPE';
export const ADMINISTRATION_EXPENSE_TYPE = 'ADMINISTRATION_EXPENSE_TYPE';
export const ADMINISTRATION_COUNTRY = 'ADMINISTRATION_COUNTRY';
export const ADMINISTRATION_CITY = 'ADMINISTRATION_CITY';


export const SUBJECTS = [USER, ROLE, CURRENCY, LAYOUT, COMPANY];
