export const ADMINISTRATION_CURRENCY_PATH = '/currencies';
export const ADMINISTRATION_CHART_ACCOUNT_PATH = '/chart-accounts';
export const ADMINISTRATION_BRAND_PATH = '/brands';
export const ADMINISTRATION_CATEGORY_PATH = '/categories';
export const ADMINISTRATION_TRANSACTION_TYPE_PATH = '/transaction-types';
export const ADMINISTRATION_TAX_TYPE_PATH = '/tax-types';
export const ADMINISTRATION_UNIT_OF_MEASURE_PATH = 'ADMINISTRATION_UNIT_OF_MEASURE_PATH';
export const ADMINISTRATION_PAYMENT_METHOD_PATH = 'ADMINISTRATION_PAYMENT_METHOD_PATH';
export const ADMINISTRATION_INCOME_TYPE_PATH = 'ADMINISTRATION_INCOME_TYPE_PATH';
export const ADMINISTRATION_EXPENSE_TYPE_PATH = 'ADMINISTRATION_EXPENSE_TYPE_PATH';
export const ADMINISTRATION_COUNTRY_PATH = 'ADMINISTRATION_COUNTRY_PATH';
export const ADMINISTRATION_CITY_PATH = 'ADMINISTRATION_CITY_PATH';


